/********************************************************************************
** Form generated from reading UI file 'UI_MotorDebug.ui'
**
** Created by: Qt User Interface Compiler version 5.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_UI_MOTORDEBUG_H
#define UI_UI_MOTORDEBUG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MotorDebugWidget
{
public:
    QLabel *LB_Show7;
    QLabel *LB_Show6;
    QLabel *LB_Show9;
    QPushButton *PB_AxisAlarmClear;
    QLabel *LB_Show8;
    QPushButton *PB_AxisEnable;
    QLabel *LB_Show29;
    QLabel *LB_AxisSelectToolbar;
    QLabel *LB_Show5_2;
    QPushButton *PB_AxisSave;
    QLabel *LB_Show11;
    QLabel *LB_Show10;
    QLabel *LB_Show16;
    QLineEdit *LE_HomeOffset;
    QLabel *LB_Show16_4;
    QLineEdit *LE_StartSpeed;
    QLineEdit *LE_DecSpeedTime;
    QLabel *LB_Show16_3;
    QLabel *LB_Show12;
    QLabel *LB_Show15;
    QLineEdit *LE_MaxSpeed;
    QLineEdit *LE_HomeSpeed;
    QLineEdit *LE_AccSpeedTime;
    QLabel *LB_Show16_2;
    QLabel *LB_Show14;
    QLabel *LB_Show4;
    QComboBox *CB_AxisSelect;
    QLabel *LB_Ready;
    QLabel *LB_Status_Limit_Minus;
    QLabel *LB_OriginalPoint;
    QLabel *LB_Show30;
    QLabel *LB_Status_Enable;
    QLabel *LB_NegativeLimit;
    QLabel *LB_Status_Aralm;
    QLabel *LB_Alarm;
    QLabel *LB_Status_Limit_Plus;
    QLabel *LB_Status_Stop;
    QLabel *LB_Enable;
    QLabel *LB_Status_Inplace;
    QLabel *LB_AxisStatus;
    QLabel *LB_PositivePoleLimit;
    QLabel *LB_Status_Origin;
    QLabel *LB_Status_Ready;
    QLabel *LB_Stop;
    QLabel *LB_InPlace;
    QLabel *LB_Show32_2;
    QLabel *LB_Show32;
    QLabel *LB_Show31;
    QLabel *LB_Show13;
    QLabel *LB_SpeedSetVal;
    QLabel *LB_Show19;
    QLabel *LB_Show20;
    QLabel *LB_Show17;
    QLabel *LB_Show18;
    QLabel *LB_Show31_2;
    QLabel *LB_PointFBVal;
    QLabel *LB_SpeedFBVal;
    QLabel *LB_PointSetVal;
    QLabel *LB_Show28;
    QPushButton *PB_AxisAdvance;
    QLabel *LB_Show27;
    QLabel *LB_Show25;
    QLabel *LB_Show22;
    QPushButton *PB_AxisRetreat;
    QLabel *LB_Show23;
    QLabel *LB_Show21;
    QPushButton *PB_AxisMove;
    QLineEdit *LE_AxisMoveVel;
    QLineEdit *LE_AxisMoveTargetVel;
    QPushButton *PB_AxisGoHome;
    QLabel *LB_Show26;
    QPushButton *PB_AxisStop;
    QComboBox *CB_MoveModel;

    void setupUi(QWidget *MotorDebugWidget)
    {
        if (MotorDebugWidget->objectName().isEmpty())
            MotorDebugWidget->setObjectName(QStringLiteral("MotorDebugWidget"));
        MotorDebugWidget->resize(950, 649);
        MotorDebugWidget->setMinimumSize(QSize(950, 649));
        MotorDebugWidget->setMaximumSize(QSize(950, 649));
        LB_Show7 = new QLabel(MotorDebugWidget);
        LB_Show7->setObjectName(QStringLiteral("LB_Show7"));
        LB_Show7->setGeometry(QRect(727, 17, 211, 215));
        LB_Show7->setFrameShape(QFrame::NoFrame);
        LB_Show6 = new QLabel(MotorDebugWidget);
        LB_Show6->setObjectName(QStringLiteral("LB_Show6"));
        LB_Show6->setGeometry(QRect(10, 247, 461, 175));
        LB_Show6->setFrameShape(QFrame::NoFrame);
        LB_Show9 = new QLabel(MotorDebugWidget);
        LB_Show9->setObjectName(QStringLiteral("LB_Show9"));
        LB_Show9->setGeometry(QRect(487, 247, 451, 175));
        LB_Show9->setFrameShape(QFrame::NoFrame);
        PB_AxisAlarmClear = new QPushButton(MotorDebugWidget);
        PB_AxisAlarmClear->setObjectName(QStringLiteral("PB_AxisAlarmClear"));
        PB_AxisAlarmClear->setGeometry(QRect(767, 147, 140, 60));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisAlarmClear->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font.setPointSize(10);
        PB_AxisAlarmClear->setFont(font);
        LB_Show8 = new QLabel(MotorDebugWidget);
        LB_Show8->setObjectName(QStringLiteral("LB_Show8"));
        LB_Show8->setGeometry(QRect(240, 17, 471, 215));
        LB_Show8->setFrameShape(QFrame::NoFrame);
        PB_AxisEnable = new QPushButton(MotorDebugWidget);
        PB_AxisEnable->setObjectName(QStringLiteral("PB_AxisEnable"));
        PB_AxisEnable->setGeometry(QRect(767, 67, 140, 60));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisEnable->setPalette(palette1);
        PB_AxisEnable->setFont(font);
        LB_Show29 = new QLabel(MotorDebugWidget);
        LB_Show29->setObjectName(QStringLiteral("LB_Show29"));
        LB_Show29->setGeometry(QRect(747, 547, 190, 91));
        LB_Show29->setFrameShape(QFrame::NoFrame);
        LB_AxisSelectToolbar = new QLabel(MotorDebugWidget);
        LB_AxisSelectToolbar->setObjectName(QStringLiteral("LB_AxisSelectToolbar"));
        LB_AxisSelectToolbar->setGeometry(QRect(10, 17, 215, 215));
        LB_AxisSelectToolbar->setFrameShape(QFrame::NoFrame);
        LB_Show5_2 = new QLabel(MotorDebugWidget);
        LB_Show5_2->setObjectName(QStringLiteral("LB_Show5_2"));
        LB_Show5_2->setGeometry(QRect(807, 20, 55, 21));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show5_2->setPalette(palette2);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font1.setPointSize(12);
        LB_Show5_2->setFont(font1);
        LB_Show5_2->setFrameShape(QFrame::NoFrame);
        PB_AxisSave = new QPushButton(MotorDebugWidget);
        PB_AxisSave->setObjectName(QStringLiteral("PB_AxisSave"));
        PB_AxisSave->setGeometry(QRect(775, 564, 140, 60));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisSave->setPalette(palette3);
        PB_AxisSave->setFont(font);
        LB_Show11 = new QLabel(MotorDebugWidget);
        LB_Show11->setObjectName(QStringLiteral("LB_Show11"));
        LB_Show11->setGeometry(QRect(747, 437, 190, 95));
        LB_Show11->setFrameShape(QFrame::NoFrame);
        LB_Show10 = new QLabel(MotorDebugWidget);
        LB_Show10->setObjectName(QStringLiteral("LB_Show10"));
        LB_Show10->setGeometry(QRect(10, 435, 721, 205));
        LB_Show10->setFrameShape(QFrame::NoFrame);
        LB_Show16 = new QLabel(MotorDebugWidget);
        LB_Show16->setObjectName(QStringLiteral("LB_Show16"));
        LB_Show16->setGeometry(QRect(250, 128, 81, 31));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show16->setPalette(palette4);
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font2.setPointSize(11);
        LB_Show16->setFont(font2);
        LE_HomeOffset = new QLineEdit(MotorDebugWidget);
        LE_HomeOffset->setObjectName(QStringLiteral("LE_HomeOffset"));
        LE_HomeOffset->setGeometry(QRect(330, 188, 125, 31));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_HomeOffset->setPalette(palette5);
        LE_HomeOffset->setFont(font);
        LE_HomeOffset->setContextMenuPolicy(Qt::NoContextMenu);
        LB_Show16_4 = new QLabel(MotorDebugWidget);
        LB_Show16_4->setObjectName(QStringLiteral("LB_Show16_4"));
        LB_Show16_4->setGeometry(QRect(480, 188, 81, 31));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show16_4->setPalette(palette6);
        LB_Show16_4->setFont(font2);
        LE_StartSpeed = new QLineEdit(MotorDebugWidget);
        LE_StartSpeed->setObjectName(QStringLiteral("LE_StartSpeed"));
        LE_StartSpeed->setGeometry(QRect(330, 68, 125, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_StartSpeed->setPalette(palette7);
        LE_StartSpeed->setFont(font);
        LE_StartSpeed->setContextMenuPolicy(Qt::NoContextMenu);
        LE_DecSpeedTime = new QLineEdit(MotorDebugWidget);
        LE_DecSpeedTime->setObjectName(QStringLiteral("LE_DecSpeedTime"));
        LE_DecSpeedTime->setGeometry(QRect(560, 128, 125, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_DecSpeedTime->setPalette(palette8);
        LE_DecSpeedTime->setFont(font);
        LE_DecSpeedTime->setContextMenuPolicy(Qt::NoContextMenu);
        LB_Show16_3 = new QLabel(MotorDebugWidget);
        LB_Show16_3->setObjectName(QStringLiteral("LB_Show16_3"));
        LB_Show16_3->setGeometry(QRect(250, 188, 81, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show16_3->setPalette(palette9);
        LB_Show16_3->setFont(font2);
        LB_Show12 = new QLabel(MotorDebugWidget);
        LB_Show12->setObjectName(QStringLiteral("LB_Show12"));
        LB_Show12->setGeometry(QRect(440, 21, 71, 30));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show12->setPalette(palette10);
        LB_Show12->setFont(font1);
        LB_Show12->setFrameShape(QFrame::NoFrame);
        LB_Show15 = new QLabel(MotorDebugWidget);
        LB_Show15->setObjectName(QStringLiteral("LB_Show15"));
        LB_Show15->setGeometry(QRect(480, 68, 81, 31));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show15->setPalette(palette11);
        LB_Show15->setFont(font2);
        LE_MaxSpeed = new QLineEdit(MotorDebugWidget);
        LE_MaxSpeed->setObjectName(QStringLiteral("LE_MaxSpeed"));
        LE_MaxSpeed->setGeometry(QRect(560, 68, 125, 31));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_MaxSpeed->setPalette(palette12);
        LE_MaxSpeed->setFont(font);
        LE_MaxSpeed->setContextMenuPolicy(Qt::NoContextMenu);
        LE_HomeSpeed = new QLineEdit(MotorDebugWidget);
        LE_HomeSpeed->setObjectName(QStringLiteral("LE_HomeSpeed"));
        LE_HomeSpeed->setGeometry(QRect(560, 188, 125, 31));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_HomeSpeed->setPalette(palette13);
        LE_HomeSpeed->setFont(font);
        LE_HomeSpeed->setContextMenuPolicy(Qt::NoContextMenu);
        LE_AccSpeedTime = new QLineEdit(MotorDebugWidget);
        LE_AccSpeedTime->setObjectName(QStringLiteral("LE_AccSpeedTime"));
        LE_AccSpeedTime->setGeometry(QRect(330, 128, 125, 31));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_AccSpeedTime->setPalette(palette14);
        LE_AccSpeedTime->setFont(font);
        LE_AccSpeedTime->setContextMenuPolicy(Qt::NoContextMenu);
        LB_Show16_2 = new QLabel(MotorDebugWidget);
        LB_Show16_2->setObjectName(QStringLiteral("LB_Show16_2"));
        LB_Show16_2->setGeometry(QRect(480, 128, 81, 31));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show16_2->setPalette(palette15);
        LB_Show16_2->setFont(font2);
        LB_Show14 = new QLabel(MotorDebugWidget);
        LB_Show14->setObjectName(QStringLiteral("LB_Show14"));
        LB_Show14->setGeometry(QRect(250, 68, 81, 31));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show14->setPalette(palette16);
        LB_Show14->setFont(font2);
        LB_Show4 = new QLabel(MotorDebugWidget);
        LB_Show4->setObjectName(QStringLiteral("LB_Show4"));
        LB_Show4->setGeometry(QRect(111, 20, 31, 21));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show4->setPalette(palette17);
        LB_Show4->setFont(font1);
        LB_Show4->setFrameShape(QFrame::NoFrame);
        CB_AxisSelect = new QComboBox(MotorDebugWidget);
        CB_AxisSelect->setObjectName(QStringLiteral("CB_AxisSelect"));
        CB_AxisSelect->setGeometry(QRect(30, 62, 180, 45));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush2(QColor(0, 85, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::Link, brush2);
        QBrush brush3(QColor(65, 125, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::LinkVisited, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Link, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush3);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Link, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush3);
        CB_AxisSelect->setPalette(palette18);
        CB_AxisSelect->setFont(font1);
        CB_AxisSelect->setFrame(false);
        LB_Ready = new QLabel(MotorDebugWidget);
        LB_Ready->setObjectName(QStringLiteral("LB_Ready"));
        LB_Ready->setGeometry(QRect(70, 380, 55, 21));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Ready->setPalette(palette19);
        LB_Ready->setFont(font1);
        LB_Ready->setFrameShape(QFrame::NoFrame);
        LB_Status_Limit_Minus = new QLabel(MotorDebugWidget);
        LB_Status_Limit_Minus->setObjectName(QStringLiteral("LB_Status_Limit_Minus"));
        LB_Status_Limit_Minus->setGeometry(QRect(260, 337, 18, 18));
        LB_Status_Limit_Minus->setFrameShape(QFrame::NoFrame);
        LB_Status_Limit_Minus->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/NoEnable.png")));
        LB_Status_Limit_Minus->setScaledContents(true);
        LB_OriginalPoint = new QLabel(MotorDebugWidget);
        LB_OriginalPoint->setObjectName(QStringLiteral("LB_OriginalPoint"));
        LB_OriginalPoint->setGeometry(QRect(70, 333, 55, 21));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_OriginalPoint->setPalette(palette20);
        LB_OriginalPoint->setFont(font1);
        LB_OriginalPoint->setFrameShape(QFrame::NoFrame);
        LB_Show30 = new QLabel(MotorDebugWidget);
        LB_Show30->setObjectName(QStringLiteral("LB_Show30"));
        LB_Show30->setGeometry(QRect(210, 248, 61, 30));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show30->setPalette(palette21);
        LB_Show30->setFont(font1);
        LB_Show30->setFrameShape(QFrame::NoFrame);
        LB_Status_Enable = new QLabel(MotorDebugWidget);
        LB_Status_Enable->setObjectName(QStringLiteral("LB_Status_Enable"));
        LB_Status_Enable->setGeometry(QRect(370, 337, 18, 18));
        LB_Status_Enable->setFrameShape(QFrame::NoFrame);
        LB_Status_Enable->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/Enable.png")));
        LB_Status_Enable->setScaledContents(true);
        LB_NegativeLimit = new QLabel(MotorDebugWidget);
        LB_NegativeLimit->setObjectName(QStringLiteral("LB_NegativeLimit"));
        LB_NegativeLimit->setGeometry(QRect(290, 333, 55, 21));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_NegativeLimit->setPalette(palette22);
        LB_NegativeLimit->setFont(font1);
        LB_NegativeLimit->setFrameShape(QFrame::NoFrame);
        LB_Status_Aralm = new QLabel(MotorDebugWidget);
        LB_Status_Aralm->setObjectName(QStringLiteral("LB_Status_Aralm"));
        LB_Status_Aralm->setGeometry(QRect(260, 383, 18, 18));
        LB_Status_Aralm->setFrameShape(QFrame::NoFrame);
        LB_Status_Aralm->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/NoEnable.png")));
        LB_Status_Aralm->setScaledContents(true);
        LB_Alarm = new QLabel(MotorDebugWidget);
        LB_Alarm->setObjectName(QStringLiteral("LB_Alarm"));
        LB_Alarm->setGeometry(QRect(290, 380, 55, 21));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Alarm->setPalette(palette23);
        LB_Alarm->setFont(font1);
        LB_Alarm->setFrameShape(QFrame::NoFrame);
        LB_Status_Limit_Plus = new QLabel(MotorDebugWidget);
        LB_Status_Limit_Plus->setObjectName(QStringLiteral("LB_Status_Limit_Plus"));
        LB_Status_Limit_Plus->setGeometry(QRect(150, 337, 18, 18));
        LB_Status_Limit_Plus->setFrameShape(QFrame::NoFrame);
        LB_Status_Limit_Plus->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/NoEnable.png")));
        LB_Status_Limit_Plus->setScaledContents(true);
        LB_Status_Stop = new QLabel(MotorDebugWidget);
        LB_Status_Stop->setObjectName(QStringLiteral("LB_Status_Stop"));
        LB_Status_Stop->setGeometry(QRect(370, 383, 18, 18));
        LB_Status_Stop->setFrameShape(QFrame::NoFrame);
        LB_Status_Stop->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/NoEnable.png")));
        LB_Status_Stop->setScaledContents(true);
        LB_Enable = new QLabel(MotorDebugWidget);
        LB_Enable->setObjectName(QStringLiteral("LB_Enable"));
        LB_Enable->setGeometry(QRect(400, 333, 55, 21));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Enable->setPalette(palette24);
        LB_Enable->setFont(font1);
        LB_Enable->setFrameShape(QFrame::NoFrame);
        LB_Status_Inplace = new QLabel(MotorDebugWidget);
        LB_Status_Inplace->setObjectName(QStringLiteral("LB_Status_Inplace"));
        LB_Status_Inplace->setGeometry(QRect(150, 383, 18, 18));
        LB_Status_Inplace->setFrameShape(QFrame::NoFrame);
        LB_Status_Inplace->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/NoEnable.png")));
        LB_Status_Inplace->setScaledContents(true);
        LB_AxisStatus = new QLabel(MotorDebugWidget);
        LB_AxisStatus->setObjectName(QStringLiteral("LB_AxisStatus"));
        LB_AxisStatus->setGeometry(QRect(40, 285, 401, 30));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_AxisStatus->setPalette(palette25);
        LB_AxisStatus->setFont(font1);
        LB_AxisStatus->setFrameShape(QFrame::NoFrame);
        LB_PositivePoleLimit = new QLabel(MotorDebugWidget);
        LB_PositivePoleLimit->setObjectName(QStringLiteral("LB_PositivePoleLimit"));
        LB_PositivePoleLimit->setGeometry(QRect(180, 333, 55, 21));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_PositivePoleLimit->setPalette(palette26);
        LB_PositivePoleLimit->setFont(font1);
        LB_PositivePoleLimit->setFrameShape(QFrame::NoFrame);
        LB_Status_Origin = new QLabel(MotorDebugWidget);
        LB_Status_Origin->setObjectName(QStringLiteral("LB_Status_Origin"));
        LB_Status_Origin->setGeometry(QRect(40, 337, 18, 18));
        LB_Status_Origin->setFrameShape(QFrame::NoFrame);
        LB_Status_Origin->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/Enable.png")));
        LB_Status_Origin->setScaledContents(true);
        LB_Status_Ready = new QLabel(MotorDebugWidget);
        LB_Status_Ready->setObjectName(QStringLiteral("LB_Status_Ready"));
        LB_Status_Ready->setGeometry(QRect(40, 383, 18, 18));
        LB_Status_Ready->setFrameShape(QFrame::NoFrame);
        LB_Status_Ready->setPixmap(QPixmap(QString::fromUtf8("../../FilmTrimmer_\344\270\273\351\241\265\351\235\242\344\277\256\346\224\271/FilmTrimmer/Image/Enable.png")));
        LB_Status_Ready->setScaledContents(true);
        LB_Stop = new QLabel(MotorDebugWidget);
        LB_Stop->setObjectName(QStringLiteral("LB_Stop"));
        LB_Stop->setGeometry(QRect(400, 380, 55, 21));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Stop->setPalette(palette27);
        LB_Stop->setFont(font1);
        LB_Stop->setFrameShape(QFrame::NoFrame);
        LB_InPlace = new QLabel(MotorDebugWidget);
        LB_InPlace->setObjectName(QStringLiteral("LB_InPlace"));
        LB_InPlace->setGeometry(QRect(180, 380, 55, 21));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_InPlace->setPalette(palette28);
        LB_InPlace->setFont(font1);
        LB_InPlace->setFrameShape(QFrame::NoFrame);
        LB_Show32_2 = new QLabel(MotorDebugWidget);
        LB_Show32_2->setObjectName(QStringLiteral("LB_Show32_2"));
        LB_Show32_2->setGeometry(QRect(890, 383, 35, 21));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show32_2->setPalette(palette29);
        LB_Show32_2->setFont(font);
        LB_Show32 = new QLabel(MotorDebugWidget);
        LB_Show32->setObjectName(QStringLiteral("LB_Show32"));
        LB_Show32->setGeometry(QRect(690, 384, 35, 21));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show32->setPalette(palette30);
        LB_Show32->setFont(font);
        LB_Show31 = new QLabel(MotorDebugWidget);
        LB_Show31->setObjectName(QStringLiteral("LB_Show31"));
        LB_Show31->setGeometry(QRect(690, 334, 35, 21));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show31->setPalette(palette31);
        LB_Show31->setFont(font);
        LB_Show13 = new QLabel(MotorDebugWidget);
        LB_Show13->setObjectName(QStringLiteral("LB_Show13"));
        LB_Show13->setGeometry(QRect(665, 253, 91, 30));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show13->setPalette(palette32);
        LB_Show13->setFont(font1);
        LB_Show13->setFrameShape(QFrame::NoFrame);
        LB_SpeedSetVal = new QLabel(MotorDebugWidget);
        LB_SpeedSetVal->setObjectName(QStringLiteral("LB_SpeedSetVal"));
        LB_SpeedSetVal->setGeometry(QRect(780, 330, 101, 31));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_SpeedSetVal->setPalette(palette33);
        LB_SpeedSetVal->setFont(font2);
        LB_SpeedSetVal->setFrameShape(QFrame::NoFrame);
        LB_Show19 = new QLabel(MotorDebugWidget);
        LB_Show19->setObjectName(QStringLiteral("LB_Show19"));
        LB_Show19->setGeometry(QRect(500, 330, 61, 31));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show19->setPalette(palette34);
        LB_Show19->setFont(font2);
        LB_Show19->setFrameShape(QFrame::NoFrame);
        LB_Show20 = new QLabel(MotorDebugWidget);
        LB_Show20->setObjectName(QStringLiteral("LB_Show20"));
        LB_Show20->setGeometry(QRect(500, 380, 61, 31));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show20->setPalette(palette35);
        LB_Show20->setFont(font2);
        LB_Show20->setFrameShape(QFrame::NoFrame);
        LB_Show17 = new QLabel(MotorDebugWidget);
        LB_Show17->setObjectName(QStringLiteral("LB_Show17"));
        LB_Show17->setGeometry(QRect(590, 290, 41, 21));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show17->setPalette(palette36);
        LB_Show17->setFont(font2);
        LB_Show17->setFrameShape(QFrame::NoFrame);
        LB_Show18 = new QLabel(MotorDebugWidget);
        LB_Show18->setObjectName(QStringLiteral("LB_Show18"));
        LB_Show18->setGeometry(QRect(780, 290, 41, 21));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show18->setPalette(palette37);
        LB_Show18->setFont(font2);
        LB_Show18->setFrameShape(QFrame::NoFrame);
        LB_Show31_2 = new QLabel(MotorDebugWidget);
        LB_Show31_2->setObjectName(QStringLiteral("LB_Show31_2"));
        LB_Show31_2->setGeometry(QRect(890, 333, 35, 21));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show31_2->setPalette(palette38);
        LB_Show31_2->setFont(font);
        LB_PointFBVal = new QLabel(MotorDebugWidget);
        LB_PointFBVal->setObjectName(QStringLiteral("LB_PointFBVal"));
        LB_PointFBVal->setGeometry(QRect(580, 380, 101, 31));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_PointFBVal->setPalette(palette39);
        LB_PointFBVal->setFont(font2);
        LB_PointFBVal->setFrameShape(QFrame::NoFrame);
        LB_SpeedFBVal = new QLabel(MotorDebugWidget);
        LB_SpeedFBVal->setObjectName(QStringLiteral("LB_SpeedFBVal"));
        LB_SpeedFBVal->setGeometry(QRect(780, 380, 101, 31));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_SpeedFBVal->setPalette(palette40);
        LB_SpeedFBVal->setFont(font2);
        LB_SpeedFBVal->setFrameShape(QFrame::NoFrame);
        LB_PointSetVal = new QLabel(MotorDebugWidget);
        LB_PointSetVal->setObjectName(QStringLiteral("LB_PointSetVal"));
        LB_PointSetVal->setGeometry(QRect(580, 330, 101, 31));
        QPalette palette41;
        palette41.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette41.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette41.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_PointSetVal->setPalette(palette41);
        LB_PointSetVal->setFont(font2);
        LB_PointSetVal->setFrameShape(QFrame::NoFrame);
        LB_Show28 = new QLabel(MotorDebugWidget);
        LB_Show28->setObjectName(QStringLiteral("LB_Show28"));
        LB_Show28->setGeometry(QRect(370, 457, 16, 181));
        QPalette palette42;
        QBrush brush4(QColor(0, 0, 255, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette42.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette42.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette42.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show28->setPalette(palette42);
        PB_AxisAdvance = new QPushButton(MotorDebugWidget);
        PB_AxisAdvance->setObjectName(QStringLiteral("PB_AxisAdvance"));
        PB_AxisAdvance->setGeometry(QRect(430, 581, 120, 45));
        QPalette palette43;
        palette43.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette43.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette43.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisAdvance->setPalette(palette43);
        PB_AxisAdvance->setFont(font);
        LB_Show27 = new QLabel(MotorDebugWidget);
        LB_Show27->setObjectName(QStringLiteral("LB_Show27"));
        LB_Show27->setGeometry(QRect(670, 539, 35, 21));
        QPalette palette44;
        palette44.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette44.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette44.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show27->setPalette(palette44);
        LB_Show27->setFont(font);
        LB_Show25 = new QLabel(MotorDebugWidget);
        LB_Show25->setObjectName(QStringLiteral("LB_Show25"));
        LB_Show25->setGeometry(QRect(430, 537, 35, 21));
        QPalette palette45;
        palette45.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette45.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette45.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show25->setPalette(palette45);
        LB_Show25->setFont(font1);
        LB_Show22 = new QLabel(MotorDebugWidget);
        LB_Show22->setObjectName(QStringLiteral("LB_Show22"));
        LB_Show22->setGeometry(QRect(29, 487, 71, 21));
        QPalette palette46;
        palette46.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette46.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette46.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show22->setPalette(palette46);
        LB_Show22->setFont(font1);
        PB_AxisRetreat = new QPushButton(MotorDebugWidget);
        PB_AxisRetreat->setObjectName(QStringLiteral("PB_AxisRetreat"));
        PB_AxisRetreat->setGeometry(QRect(590, 581, 120, 45));
        QPalette palette47;
        palette47.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette47.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette47.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisRetreat->setPalette(palette47);
        PB_AxisRetreat->setFont(font);
        LB_Show23 = new QLabel(MotorDebugWidget);
        LB_Show23->setObjectName(QStringLiteral("LB_Show23"));
        LB_Show23->setGeometry(QRect(29, 537, 35, 21));
        QPalette palette48;
        palette48.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette48.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette48.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show23->setPalette(palette48);
        LB_Show23->setFont(font1);
        LB_Show21 = new QLabel(MotorDebugWidget);
        LB_Show21->setObjectName(QStringLiteral("LB_Show21"));
        LB_Show21->setGeometry(QRect(350, 440, 55, 21));
        QPalette palette49;
        palette49.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette49.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette49.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show21->setPalette(palette49);
        LB_Show21->setFont(font1);
        LB_Show21->setFrameShape(QFrame::NoFrame);
        PB_AxisMove = new QPushButton(MotorDebugWidget);
        PB_AxisMove->setObjectName(QStringLiteral("PB_AxisMove"));
        PB_AxisMove->setGeometry(QRect(49, 581, 120, 45));
        QPalette palette50;
        palette50.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette50.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette50.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisMove->setPalette(palette50);
        PB_AxisMove->setFont(font);
        LE_AxisMoveVel = new QLineEdit(MotorDebugWidget);
        LE_AxisMoveVel->setObjectName(QStringLiteral("LE_AxisMoveVel"));
        LE_AxisMoveVel->setGeometry(QRect(500, 532, 161, 35));
        QPalette palette51;
        palette51.setBrush(QPalette::Active, QPalette::Text, brush);
        palette51.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette51.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_AxisMoveVel->setPalette(palette51);
        LE_AxisMoveVel->setFont(font);
        LE_AxisMoveTargetVel = new QLineEdit(MotorDebugWidget);
        LE_AxisMoveTargetVel->setObjectName(QStringLiteral("LE_AxisMoveTargetVel"));
        LE_AxisMoveTargetVel->setGeometry(QRect(93, 532, 161, 35));
        QPalette palette52;
        palette52.setBrush(QPalette::Active, QPalette::Text, brush);
        palette52.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette52.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        LE_AxisMoveTargetVel->setPalette(palette52);
        LE_AxisMoveTargetVel->setFont(font);
        PB_AxisGoHome = new QPushButton(MotorDebugWidget);
        PB_AxisGoHome->setObjectName(QStringLiteral("PB_AxisGoHome"));
        PB_AxisGoHome->setGeometry(QRect(209, 581, 120, 45));
        QPalette palette53;
        palette53.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette53.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette53.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisGoHome->setPalette(palette53);
        PB_AxisGoHome->setFont(font);
        LB_Show26 = new QLabel(MotorDebugWidget);
        LB_Show26->setObjectName(QStringLiteral("LB_Show26"));
        LB_Show26->setGeometry(QRect(260, 539, 35, 21));
        QPalette palette54;
        palette54.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette54.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette54.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LB_Show26->setPalette(palette54);
        LB_Show26->setFont(font);
        PB_AxisStop = new QPushButton(MotorDebugWidget);
        PB_AxisStop->setObjectName(QStringLiteral("PB_AxisStop"));
        PB_AxisStop->setGeometry(QRect(775, 453, 140, 60));
        QPalette palette55;
        QBrush brush5(QColor(255, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette55.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette55.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette55.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        PB_AxisStop->setPalette(palette55);
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(16);
        PB_AxisStop->setFont(font3);
        CB_MoveModel = new QComboBox(MotorDebugWidget);
        CB_MoveModel->setObjectName(QStringLiteral("CB_MoveModel"));
        CB_MoveModel->setGeometry(QRect(500, 470, 161, 41));
        QPalette palette56;
        palette56.setBrush(QPalette::Active, QPalette::Text, brush);
        palette56.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette56.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        CB_MoveModel->setPalette(palette56);
        CB_MoveModel->setFont(font2);

        retranslateUi(MotorDebugWidget);

        QMetaObject::connectSlotsByName(MotorDebugWidget);
    } // setupUi

    void retranslateUi(QWidget *MotorDebugWidget)
    {
        MotorDebugWidget->setWindowTitle(QApplication::translate("MotorDebugWidget", "Form", 0));
        LB_Show7->setText(QString());
        LB_Show6->setText(QString());
        LB_Show9->setText(QString());
        PB_AxisAlarmClear->setText(QApplication::translate("MotorDebugWidget", " \346\212\245\350\255\246\346\270\205\351\231\244  ", 0));
        LB_Show8->setText(QString());
        PB_AxisEnable->setText(QApplication::translate("MotorDebugWidget", " \350\275\264\344\275\277\350\203\275    ", 0));
        LB_Show29->setText(QString());
        LB_AxisSelectToolbar->setText(QString());
        LB_Show5_2->setText(QApplication::translate("MotorDebugWidget", "\350\275\264\345\207\206\345\244\207", 0));
        PB_AxisSave->setText(QApplication::translate("MotorDebugWidget", "  \344\277\235\345\255\230", 0));
        LB_Show11->setText(QString());
        LB_Show10->setText(QString());
        LB_Show16->setText(QApplication::translate("MotorDebugWidget", "\345\212\240\351\200\237\346\227\266\351\227\264:", 0));
        LB_Show16_4->setText(QApplication::translate("MotorDebugWidget", "\345\275\222\351\233\266\351\200\237\345\272\246:", 0));
        LB_Show16_3->setText(QApplication::translate("MotorDebugWidget", "\351\233\266\347\202\271\345\201\217\347\247\273:", 0));
        LB_Show12->setText(QApplication::translate("MotorDebugWidget", "\345\217\202\346\225\260\350\256\276\345\256\232", 0));
        LB_Show15->setText(QApplication::translate("MotorDebugWidget", "\346\234\200\345\244\247\351\200\237\345\272\246:", 0));
        LB_Show16_2->setText(QApplication::translate("MotorDebugWidget", "\345\207\217\351\200\237\346\227\266\351\227\264:", 0));
        LB_Show14->setText(QApplication::translate("MotorDebugWidget", "\345\220\257\345\212\250\351\200\237\345\272\246\357\274\232", 0));
        LB_Show4->setText(QApplication::translate("MotorDebugWidget", "\350\275\264", 0));
        LB_Ready->setText(QApplication::translate("MotorDebugWidget", "\345\207\206\345\244\207\345\245\275", 0));
        LB_Status_Limit_Minus->setText(QString());
        LB_OriginalPoint->setText(QApplication::translate("MotorDebugWidget", "\345\216\237\347\202\271\344\275\215", 0));
        LB_Show30->setText(QApplication::translate("MotorDebugWidget", "\350\275\264\347\212\266\346\200\201", 0));
        LB_Status_Enable->setText(QString());
        LB_NegativeLimit->setText(QApplication::translate("MotorDebugWidget", "\350\264\237\346\236\201\351\231\220", 0));
        LB_Status_Aralm->setText(QString());
        LB_Alarm->setText(QApplication::translate("MotorDebugWidget", "\346\212\245\350\255\246", 0));
        LB_Status_Limit_Plus->setText(QString());
        LB_Status_Stop->setText(QString());
        LB_Enable->setText(QApplication::translate("MotorDebugWidget", "\344\275\277\350\203\275", 0));
        LB_Status_Inplace->setText(QString());
        LB_AxisStatus->setText(QApplication::translate("MotorDebugWidget", "\346\234\252\350\277\236\346\216\245", 0));
        LB_PositivePoleLimit->setText(QApplication::translate("MotorDebugWidget", "\346\255\243\346\236\201\351\231\220", 0));
        LB_Status_Origin->setText(QString());
        LB_Status_Ready->setText(QString());
        LB_Stop->setText(QApplication::translate("MotorDebugWidget", "\346\232\202\345\201\234", 0));
        LB_InPlace->setText(QApplication::translate("MotorDebugWidget", "\345\210\260\344\275\215", 0));
        LB_Show32_2->setText(QApplication::translate("MotorDebugWidget", "mm/s", 0));
        LB_Show32->setText(QApplication::translate("MotorDebugWidget", "mm", 0));
        LB_Show31->setText(QApplication::translate("MotorDebugWidget", "mm", 0));
        LB_Show13->setText(QApplication::translate("MotorDebugWidget", "\350\275\264\350\277\220\345\212\250\345\217\215\351\246\210", 0));
        LB_SpeedSetVal->setText(QApplication::translate("MotorDebugWidget", "0", 0));
        LB_Show19->setText(QApplication::translate("MotorDebugWidget", "\350\256\276\345\256\232\345\200\274", 0));
        LB_Show20->setText(QApplication::translate("MotorDebugWidget", "\345\217\215\351\246\210\345\200\274", 0));
        LB_Show17->setText(QApplication::translate("MotorDebugWidget", "\344\275\215\347\275\256", 0));
        LB_Show18->setText(QApplication::translate("MotorDebugWidget", "\351\200\237\345\272\246", 0));
        LB_Show31_2->setText(QApplication::translate("MotorDebugWidget", "mm/s", 0));
        LB_PointFBVal->setText(QApplication::translate("MotorDebugWidget", "0", 0));
        LB_SpeedFBVal->setText(QApplication::translate("MotorDebugWidget", "0", 0));
        LB_PointSetVal->setText(QApplication::translate("MotorDebugWidget", "0", 0));
        LB_Show28->setText(QApplication::translate("MotorDebugWidget", "|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|\n"
"|", 0));
        PB_AxisAdvance->setText(QApplication::translate("MotorDebugWidget", "  \345\211\215\350\277\233", 0));
        LB_Show27->setText(QApplication::translate("MotorDebugWidget", "mm", 0));
        LB_Show25->setText(QApplication::translate("MotorDebugWidget", "\350\267\235\347\246\273", 0));
        LB_Show22->setText(QApplication::translate("MotorDebugWidget", "\347\273\235\345\257\271\347\247\273\345\212\250:", 0));
        PB_AxisRetreat->setText(QApplication::translate("MotorDebugWidget", "  \345\220\216\351\200\200", 0));
        LB_Show23->setText(QApplication::translate("MotorDebugWidget", "\344\275\215\347\275\256", 0));
        LB_Show21->setText(QApplication::translate("MotorDebugWidget", "\350\275\264\346\216\247\345\210\266", 0));
        PB_AxisMove->setText(QApplication::translate("MotorDebugWidget", "  \347\247\273\345\212\250", 0));
        PB_AxisGoHome->setText(QApplication::translate("MotorDebugWidget", "  \345\275\222\351\233\266", 0));
        LB_Show26->setText(QApplication::translate("MotorDebugWidget", "mm", 0));
        PB_AxisStop->setText(QApplication::translate("MotorDebugWidget", "\345\201\234\346\255\242", 0));
        CB_MoveModel->clear();
        CB_MoveModel->insertItems(0, QStringList()
         << QApplication::translate("MotorDebugWidget", "\347\273\235\345\257\271\347\247\273\345\212\250", 0)
         << QApplication::translate("MotorDebugWidget", "\347\202\271\345\212\250", 0)
        );
    } // retranslateUi

};

namespace Ui {
    class MotorDebugWidget: public Ui_MotorDebugWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_UI_MOTORDEBUG_H
